// User actions
export const USER_SET = 'USER_SET';
export const USER_SENDING_DATA = 'USER_SENDING_DATA';
export const USER_ERRORS = 'USER_ERRORS';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CLEAN_USER_AUTHENTICATION_ERRORS = 'CLEAN_USER_AUTHENTICATION_ERRORS';
export const USER_REGISTER = 'USER_REGISTER';

// Book actions
export const BOOK_SET = 'BOOK_SET';
export const BOOK_SET_SENDING_DATA = 'SENDING_DATA';
export const BOOK_SET_ERRORS = 'BOOK_SET_ERRORS';
export const BOOK_SET_CREATED = 'BOOK_SET_CREATED';

// Book List actions
export const BOOK_LIST_SET = 'BOOK_LIST_SET';
export const BOOK_LIST_SET_SENDING_DATA = 'BOOK_LIST_SET_SENDING_DATA';

// Activity actions
export const ACTIVITY_SET = 'ACTIVITY_SET';
export const ACTIVITY_SET_CREATED = 'ACTIVITY_SET_CREATED';
export const ACTIVITY_SET_SENDING_DATA = 'ACTIVITY_SENDING_DATA';
export const ACTIVITY_SET_ERRORS = 'ACTIVITY_SET_ERRORS';

// Activity list actions
export const ACTIVITY_LIST_SET = 'ACTIVITY_LIST_SET';
export const ACTIVITY_LIST_SET_SENDING_DATA = 'ACTIVITY_LIST_SET_SENDING_DATA';
